### ISSUE TITLE
Migrate MySQL to PostgreSQL

### ISSUE THREAD

**Issue by Almad** [dracidoupe/graveyard#193]
This requires old version to be shut down. 

[pgLoader](https://www.digitalocean.com/community/tutorials/how-to-migrate-mysql-database-to-postgres-using-pgloader) looks like a plausible solution for doing the migration.

I am not convinced there are significant advantages to the migration (besides postgres being better :D), except it would allow me to use the ddcz RDS for other projects as well :) 

It is very slightly more expensive ($0.02 vs $0.021). We could also consider Aurora, but with reserved instances, that'd be significantly more expensive ($0.096). But I think we could be up for serverless, which charges $0.07 per ACU Hour and I have no idea how much that would be, some estimates and computations would be needed. 

Aurora charges $0.119 per GB-month plus $0.22 per 1 million I/O, vs $0.137 per GB-month and $0.119 per IOPS-month on RDS for SSD, and $0.119 per GB-month $0.11 per 1 million I/O requests on magnetic. 

Also note to self: check if Heroku and RDS traffic is considered a traffic within the same AZ or as "to Internet". 

1 ACU has approximately 2 GB of memory with corresponding CPU and networking, similar to what is used in Aurora user-provisioned instances.

**Comment by Almad** [comment]
OK, so currently, minimum available aurora serverless capacity is 2ACU, hence $0.14/h, making it fairly expensive. That said, it can go to sleep on a short notice. It would need traffic research to see if we would be able to have such a significant cache-hit on the frontend that we'd be able to have it off for sufficient amount of time (my thinking is CEST overnight) to make it worth it. 

But my guess is no: if we prepay `db.t3.micro` for a year, we're at `$0.013`/hr, for 3y `$0.009`/hr, which would make Aurora 15x more expensive. I don't think there is a traffic scenario for DDCZ where it would work. 

<img width="806" alt="image" src="https://user-images.githubusercontent.com/44565/115038710-12c1a980-9ed0-11eb-93f2-3b034023d0d2.png">

**Comment by Almad** [comment]
Also, there is always someone somewhen. Few dozen users, but still. 

<img width="368" alt="image" src="https://user-images.githubusercontent.com/44565/115039928-31747000-9ed1-11eb-985f-29d65bd6b9d1.png">

**Comment by Almad** [comment]
Also actually, new Postgres plans on Heroku can do $5/mo, which is probably best price anywhere now that aws introduced paying for public IPs, plus we pay for egress.

**Comment by Almad** [comment]
fly looks even better now kinda, so yeah, postgres

![Image](https://github.com/user-attachments/assets/ab7d282d-49a3-43d7-840f-d1b3ba048a17)

**Comment by Almad** [comment]
OK, this seems to be working better than alternatives:

```
docker run -it --rm -v /volume1/software:/data dimitri/pgloader:ccl.latest pgloader /data/migration-simple.load --no-ssl-cert-verification

load database
  from mysql://user:psw@host/dracidoupe_cz
  into postgres://user:psw@host/herokudb?sslmode=allow
with include drop, create tables, create indexes, reset sequences,
     workers = 1, concurrency = 1;
```

**Comment by Almad** [comment]
Working in local theory, but not in practice:

- Somehow the DB_ env vars override URL setup
- In prod, this happens during Heroku release when reading correct variables

```
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, ddcz, sessions
Running migrations:
  Applying ddcz.0003_lesschat...Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "id" of relation "django_migrations" violates not-null constraint
DETAIL:  Failing row contains (null, ddcz, 0003_lesschat, 2025-09-03 00:17:33.077371+00).
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.heroku/python/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.heroku/python/lib/python3.9/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/.heroku/python/lib/python3.9/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/app/.heroku/python/lib/python3.9/site-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 243, in handle
    post_migrate_state = executor.migrate(
  File "/app/.heroku/python/lib/python3.9/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/app/.heroku/python/lib/python3.9/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/app/.heroku/python/lib/python3.9/site-packages/django/db/migrations/executor.py", line 228, in apply_migration
    self.record_migration(migration)
  File "/app/.heroku/python/lib/python3.9/site-packages/django/db/migrations/executor.py", line 243, in record_migration
    self.recorder.record_applied(migration.app_label, migration.name)
  File "/app/.heroku/python/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 87, in record_applied
    self.migration_qs.create(app=app, name=name)
  File "/app/.heroku/python/lib/python3.9/site-packages/django/db/models/query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "/app/.heroku/python/lib/python3.9/site-packages/django/db/models/base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/app/.heroku/python/lib/python3.9/site-packages/django/db/models/base.py", line 790, in save_base
    updated = self._save_table(
  File "/app/.heroku/python/lib/python3.9/site-packages/django/db/models/base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/app/.heroku/python/lib/python3.9/site-packages/django/db/models/base.py", line 933, in _do_insert
    return manager._insert(
  File "/app/.heroku/python/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.9/site-packages/django/db/models/query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/app/.heroku/python/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "/app/.heroku/python/lib/python3.9/site-packages/sentry_sdk/utils.py", line 1816, in runner
    return sentry_patched_function(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.9/site-packages/sentry_sdk/integrations/django/__init__.py", line 652, in execute
    result = real_execute(self, sql, params)
  File "/app/.heroku/python/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/app/.heroku/python/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/app/.heroku/python/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/app/.heroku/python/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/app/.heroku/python/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "id" of relation "django_migrations" violates not-null constraint
DETAIL:  Failing row contains (null, ddcz, 0003_lesschat, 2025-09-03 00:17:33.077371+00).
```

I suspect bad restore, but it's a problem for another day
