### ISSUE TITLE
Documentation is not being built

### ISSUE THREAD

**Issue by Almad** [dracidoupe/graveyard#261]
...since the introduction of the specific mysql client deps

```
WARNING: Discarding https://files.pythonhosted.org/packages/31/ce/7ea049b3d5929b3cce3104967ccca218a9f054517f0d15dfdaf4e76da2a0/mysqlclient-1.3.8.tar.gz#sha256=c64bc386c0b771ed6ff76de0f52e0f957f98d9e13c83b0ddb821afdbe3f5d970 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysqlclient-1.3.7.tar.gz (79 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/docs/checkouts/readthedocs.org/user_builds/ddcz/envs/latest/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-is4q40ig/mysqlclient_a113a1acb5b14b739da1e42d7ab908c9/setup.py'"'"'; __file__='"'"'/tmp/pip-install-is4q40ig/mysqlclient_a113a1acb5b14b739da1e42d7ab908c9/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ha7ym8an
         cwd: /tmp/pip-install-is4q40ig/mysqlclient_a113a1acb5b14b739da1e42d7ab908c9/
    Complete output (10 lines):
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-is4q40ig/mysqlclient_a113a1acb5b14b739da1e42d7ab908c9/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-is4q40ig/mysqlclient_a113a1acb5b14b739da1e42d7ab908c9/setup_posix.py", line 44, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-install-is4q40ig/mysqlclient_a113a1acb5b14b739da1e42d7ab908c9/setup_posix.py", line 26, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    OSError: mysql_config not found
    ----------------------------------------
```

**Comment by Almad** [comment]
<img width="227" alt="image" src="https://user-images.githubusercontent.com/44565/118237428-9d79d200-b497-11eb-8f1a-465d0f2364cb.png">
