### ISSUE TITLE
Post Office (Direct Messages)

### ISSUE THREAD

**Issue by Almad** [dracidoupe/graveyard#354]
- [x] Make sent letter visible to receiver
- [x] Delete should only delete letter for you, not for both sides
~- [ ] Make it reasonably fast~
<img width="193" alt="image" src="https://user-images.githubusercontent.com/44565/132107154-05c24ff7-e3f8-4645-b650-dc23692487b8.png">

- [x] Fix bad url somewhere
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/almad/Documents/projects/graveyard/gvenv/lib/python3.9/site-packages/django/template/base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/almad/Documents/projects/graveyard/gvenv/lib/python3.9/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/almad/Documents/projects/graveyard/gvenv/lib/python3.9/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/almad/Documents/projects/graveyard/gvenv/lib/python3.9/site-packages/django/template/base.py", line 854, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'debug_toolbar.toolbar' from '/Users/almad/Documents/projects/graveyard/gvenv/lib/python3.9/site-packages/debug_toolbar/toolbar.py'> (djdt:djdt) '__debug__/'>
2021-09-04 22:19:05 [64675] [WARNING] pathname=/Users/almad/Documents/projects/graveyard/gvenv/lib/python3.9/site-packages/django/core/handlers/base.py lineno=91 funcname=get_response Not Found: /posta/None
2021-09-04 22:19:05 [64675] [WARNING] pathname=/Users/almad/Documents/projects/graveyard/gvenv/lib/python3.9/site-packages/django/core/servers/basehttp.py lineno=124 funcname=log_message "GET /posta/None HTTP/1.1" 404 18678
```

- [x] Make sure we can display (although not sent) mailing list messages
- [x] Use timezone-aware timestamps

```
Sep 05 14:22:45 ddcz-prod app/web.1: 2021-09-05 14:22:45 [WARNING] Not Found: /posta/None 
Sep 05 14:22:45 ddcz-prod app/web.1: 2021-09-05 14:22:45 [WARNING] Not Found: /posta/None 
Sep 05 14:23:02 ddcz-prod app/web.1: /app/.heroku/python/lib/python3.7/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField Letter.date received a naive datetime (2021-09-05 14:23:01.666680) while time zone support is active. 
Sep 05 14:23:03 ddcz-prod app/web.1: 2021-09-05 14:23:03 [WARNING] Not Found: /posta/None 
Sep 05 14:23:03 ddcz-prod app/web.1: 2021-09-05 14:23:03 [WARNING] Not Found: /posta/None 

```

**Comment by Almad** [comment]
Not done until the listed bugs are fixed
