### ISSUE TITLE
Fix exception for 404s in debug mode

### ISSUE THREAD

**Issue by Almad** [dracidoupe/graveyard#70]
```
Traceback (most recent call last):
  File "/home/almad/projects/graveyard/gvenv/lib/python3.7/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'dragon.urls' from '/home/almad/projects/graveyard/dragon/urls.py'> (dragon:dragon) 'sprava/'>
DEBUG Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/almad/projects/graveyard/gvenv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/almad/projects/graveyard/gvenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/almad/projects/graveyard/gvenv/lib/python3.7/site-packages/django/urls/resolvers.py", line 527, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'dragon.urls' from '/home/almad/projects/graveyard/dragon/urls.py'> (dragon:dragon) 'sprava/'>], [<URLResolver <module 'ddcz.urls' from '/home/almad/projects/graveyard/ddcz/urls.py'> (ddcz:ddcz) ''>, <URLPattern ''>], [<URLResolver <module 'ddcz.urls' from '/home/almad/projects/graveyard/ddcz/urls.py'> (ddcz:ddcz) ''>, <URLPattern 'aktuality/' [name='news']>], [<URLResolver <module 'ddcz.urls' from '/home/almad/projects/graveyard/ddcz/urls.py'> (ddcz:ddcz) ''>, <URLPattern 'rubriky/<creative_page_slug>/' [name='common-article-list']>], [<URLResolver <module 'ddcz.urls' from '/home/almad/projects/graveyard/ddcz/urls.py'> (ddcz:ddcz) ''>, <URLPattern 'rubriky/<creative_page_slug>/koncepce/' [name='creative-page-concept']>], [<URLResolver <module 'ddcz.urls' from '/home/almad/projects/graveyard/ddcz/urls.py'> (ddcz:ddcz) ''>, <URLPattern 'rubriky/<creative_page_slug>/<int:article_id>-<article_slug>/' [name='common-article-detail']>], [<URLResolver <module 'ddcz.urls' from '/home/almad/projects/graveyard/ddcz/urls.py'> (ddcz:ddcz) ''>, <URLPattern 'seznamka/' [name='dating']>], [<URLResolver <module 'ddcz.urls' from '/home/almad/projects/graveyard/ddcz/urls.py'> (ddcz:ddcz) ''>, <URLPattern 'nastaveni/zmena-skinu/' [name='change-skin']>], [<URLResolver <module 'ddcz.urls' from '/home/almad/projects/graveyard/ddcz/urls.py'> (ddcz:ddcz) ''>, <URLPattern 'uzivatel/prihlaseni/' [name='login-action']>], [<URLResolver <module 'ddcz.urls' from '/home/almad/projects/graveyard/ddcz/urls.py'> (ddcz:ddcz) ''>, <URLPattern 'uzivatel/odhlaseni/' [name='logout-action']>], [<URLResolver <module 'ddcz.urls' from '/home/almad/projects/graveyard/ddcz/urls.py'> (ddcz:ddcz) ''>, <URLPattern 'uzivatel/reset-hesla/' [name='password-reset']>], [<URLResolver <module 'ddcz.urls' from '/home/almad/projects/graveyard/ddcz/urls.py'> (ddcz:ddcz) ''>, <URLPattern 'uzivatel/<int:user_profile_id>-<nick_slug>/' [name='user-detail']>]], 'path': 'xoxoxo4040'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/almad/projects/graveyard/gvenv/lib/python3.7/site-packages/django/template/base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/almad/projects/graveyard/gvenv/lib/python3.7/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/almad/projects/graveyard/gvenv/lib/python3.7/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/almad/projects/graveyard/gvenv/lib/python3.7/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'dragon.urls' from '/home/almad/projects/graveyard/dragon/urls.py'> (dragon:dragon) 'sprava/'>
WARNING Not Found: /xoxoxo4040

````

**Comment by Almad** [comment]
Not sure how, but is fixed. We should probably have custom 404 though
